const { chromium } = require('playwright');
const assert = require('node:assert/strict');
require('node:fs').mkdirSync('outputs/etapa-11-2', { recursive: true });
(async () => {
  const browser = await chromium.launch({ channel: 'msedge', headless: true });
  try {
    const context = await browser.newContext({ viewport: { width: 1280, height: 900 } });
    const page = await context.newPage();
    await page.addInitScript(() => {
      const now = new Date().toISOString();
      const sale = { id: 'ui-test', number: 1, date: now, status: 'completed', cashSessionId: 'ui-cash', items: [ { productId: 'a', productName: 'Produto A', unitPriceInCents: 500, quantity: 2, subtotalInCents: 1000 }, { productId: 'b', productName: 'Produto B', unitPriceInCents: 1000, quantity: 1, subtotalInCents: 1000 } ], totalInCents: 2000, payments: [{ method: 'pix', amountInCents: 2000 }] };
      localStorage.setItem('raiz-pdv:completed-sales', JSON.stringify([sale]));
      localStorage.setItem('raiz-pdv:cash', JSON.stringify({ sessions: [{ id: 'ui-cash', operatorId: 'raiz-admin', operatorName: 'Administrador Mestre', openedAt: now, openingAmountInCents: 10000, status: 'open' }], movements: [] }));
      window.print = () => { window.printCheck = { credit: document.body.classList.contains('printing-credit'), rootDisplay: getComputedStyle(document.getElementById('root')).display, saleDisplay: getComputedStyle(document.querySelector('.history-detail-overlay')).display, slips: [...document.querySelectorAll('.customer-credit-print-area .print-root')].map(el => ({ display: getComputedStyle(el).display, text: el.innerText })) }; };
    });
    await page.goto('http://127.0.0.1:5173/');
    await page.getByRole('textbox',{name:'Operador',exact:true}).fill('Admin');
    await page.getByLabel('Senha',{exact:true}).fill('123456');
    await page.getByRole('button',{name:'Entrar',exact:true}).click();
    await page.getByRole('button', { name: 'Histórico', exact: true }).click();
    await page.getByRole('button', { name: 'Ver detalhes' }).click();
    await page.getByRole('button', { name: 'Devolver produtos', exact: true }).click();
    await page.getByRole('spinbutton', { name: 'Quantidade devolvida de Produto A' }).fill('1');
    await page.getByRole('button', { name: 'Confirmar itens e continuar' }).click();
    await page.getByRole('heading', { name: '2. Como devolver o valor?' }).waitFor();
    assert.equal(await page.locator('#settlement-customer_credit').inputValue(), '5,00');
    assert.equal(await page.locator('.settlement-line').count(), 1);
    await page.screenshot({ path: 'outputs/etapa-11-2/devolucao-simplificada.png' });
    await page.getByRole('button', { name: 'Gerar crédito do cliente', exact: true }).click();
    await page.getByRole('heading', { name: 'Crédito emitido', exact: true }).waitFor();
    assert.equal(await page.locator('body > .credit-receipt-overlay').count(), 1);
    const bounds = await page.locator('.customer-credit-receipt-modal').boundingBox();
    assert.ok(bounds.height <= 868);
    assert.ok(bounds.width <= 480);
    await page.getByRole('button', { name: 'Fechar comprovante de crédito', exact: true }).waitFor({ state: 'visible' });
    await page.emulateMedia({ media: 'print' });
    await page.getByRole('button', { name: 'Imprimir comprovante do crédito (2 vias)', exact: true }).click();
    const result = await page.evaluate(() => window.printCheck);
    assert.equal(result.credit, true);
    assert.equal(result.rootDisplay, 'none');
    assert.equal(result.slips.length, 2);
    for (const slip of result.slips) { assert.equal(slip.display, 'block'); assert.match(slip.text, /CRÉDITO DE CLIENTE/); assert.match(slip.text, /5,00/); assert.match(slip.text, /CÓDIGO DE AUTORIZAÇÃO/); }
    await page.evaluate(() => document.body.classList.add('printing-credit'));
    await page.screenshot({ path: 'outputs/etapa-11-2/credito-impressao.png', fullPage: true });
    await page.pdf({ path: 'outputs/etapa-11-2/credito-impressao.pdf', preferCSSPageSize: true });
    await page.evaluate(() => document.body.classList.remove('printing-credit'));
    await page.emulateMedia({ media: 'screen' });
    await page.getByRole('button', { name: 'Fechar comprovante de crédito', exact: true }).focus();
    await page.keyboard.press('Escape');
    await page.locator('.credit-receipt-overlay').waitFor({ state: 'detached' });
    assert.equal(await page.locator('.history-detail-overlay').count(), 1);
    await page.getByRole('button', { name: 'Reimprimir comprovante' }).click();
    const salePrint = await page.evaluate(() => window.printCheck);
    assert.equal(salePrint.credit, false);
    assert.notEqual(salePrint.saleDisplay, 'none');
    assert.notEqual(salePrint.rootDisplay, 'none');
    await page.emulateMedia({ media: 'screen' });
    await page.getByRole('button', { name: 'Voltar ao histórico' }).click();
    await page.getByRole('button', { name: 'Relatórios', exact: true }).click();
    await page.waitForFunction(() => document.querySelector('.analytics-stat-green strong')?.textContent.includes('20,00'));
    assert.match(await page.locator('.analytics-financial-summary').innerText(), /Créditos emitidos[\s\S]*5,00/);
    await page.evaluate(() => {
      const key = 'raiz-pdv:sale-financial-data';
      const financial = JSON.parse(localStorage.getItem(key));
      financial.returns[0].items[0].quantity = 2;
      financial.returns[0].items[0].amountInCents = 1000;
      financial.returns[0].amountInCents = 1000;
      localStorage.setItem(key, JSON.stringify(financial));
      window.dispatchEvent(new Event('raiz-pdv:data-changed'));
    });
    await page.waitForFunction(() => document.querySelector('.analytics-stat-green strong')?.textContent.includes('20,00'));
    // Real storage events from another tab must refresh an already-open report.
    const other = await page.context().newPage();
    await other.goto('http://127.0.0.1:5173/');
    await other.evaluate(() => {
      const financialKey = 'raiz-pdv:sale-financial-data', saleKey = 'raiz-pdv:completed-sales';
      const financial = JSON.parse(localStorage.getItem(financialKey));
      const sales = JSON.parse(localStorage.getItem(saleKey));
      const credit = financial.credits[0];
      credit.balanceInCents = 0; credit.status = 'redeemed';
      financial.creditMovements.push({ id: 'ui-redeemed', creditId: credit.id, type: 'redeemed', amountInCents: 500, createdAt: new Date().toISOString(), saleId: 'ui-credit-sale' });
      sales.push({ ...sales[0], id: 'ui-credit-sale', number: 2, items: [{ productId: 'c', productName: 'Produto C', unitPriceInCents: 500, quantity: 1, subtotalInCents: 500 }], totalInCents: 500, payments: [{ method: 'customer_credit', amountInCents: 500, customerCreditId: credit.id }] });
      localStorage.setItem(financialKey, JSON.stringify(financial));
      localStorage.setItem(saleKey, JSON.stringify(sales));
    });
    await page.waitForFunction(() => document.querySelector('.analytics-stat-green strong')?.textContent.includes('25,00'));
    assert.match(await page.locator('.payment-breakdown-row').filter({ hasText: 'Crédito do cliente' }).innerText(), /5,00/);
    assert.match(await page.locator('.payment-breakdown-row').filter({ hasText: 'Pix' }).innerText(), /80%/);
    assert.match(await page.locator('.analytics-financial-summary').innerText(), /Valor recebido líquido[\s\S]*20,00/);
    await page.getByRole('button', { name: 'Histórico', exact: true }).click();
    assert.match(await page.locator('[aria-label="Totais do histórico"]').innerText(), /Vendas concluídas[\s\S]*2[\s\S]*Faturamento[\s\S]*25,00[\s\S]*Valor recebido líquido[\s\S]*20,00/);
    await page.getByRole('button', { name: 'Caixa', exact: true }).click();
    await page.locator('.cash-net-sales').waitFor();
    assert.match(await page.locator('.cash-net-sales').innerText(), /25,00[\s\S]*2 venda/);
    assert.match(await page.locator('.cash-summary-card').filter({ hasText: 'Valor recebido líquido' }).innerText(), /20,00/);
    await page.getByRole('button', { name: 'Fechar caixa', exact: true }).click();
    assert.match(await page.locator('.cash-receipt-summary').innerText(), /25,00[\s\S]*20,00[\s\S]*2 venda/);
    await page.locator('.cash-reconciliation-modal').press('Escape');
    await page.getByRole('button', { name: 'Início', exact: true }).click();
    await page.waitForFunction(() => document.querySelector('.analytics-stat-green strong')?.textContent.includes('25,00'));
    await other.evaluate(() => {
      const key = 'raiz-pdv:completed-sales', sales = JSON.parse(localStorage.getItem(key));
      sales[0].status = 'cancelled'; sales[0].cancelledAt = new Date().toISOString(); sales[0].cancellationReason = 'customer_cancelled';
      localStorage.setItem(key, JSON.stringify(sales));
    });
    await page.waitForFunction(() => document.querySelector('.analytics-stat-green strong')?.textContent.includes('5,00'));
    assert.match(await page.locator('.analytics-stat-blue strong').innerText(), /^1$/);
    await page.screenshot({ path: 'outputs/etapa-11-2/dashboard-financeiro.png' });
    await other.close();
    console.log('PASS: impressão e Esc; dashboard e relatório com faturamento original e devoluções separadas; crédito nos pagamentos; atualização na mesma aba e entre abas; cancelamento.');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
