const { chromium } = require('playwright');
const assert = require('node:assert/strict');
(async () => {
 const browser = await chromium.launch({ channel: 'msedge', headless: true });
 try {
  const context = await browser.newContext({ viewport: { width: 1280, height: 950 }, timezoneId: 'America/Sao_Paulo' });
  const page = await context.newPage();
  await page.addInitScript(() => {
   if (localStorage.getItem('operator-test-seeded')) return;
   const yesterday = new Date(Date.now() - 86400000).toISOString();
   localStorage.setItem('raiz-pdv:settings', JSON.stringify({ storeName:'Teste', address:'', phone:'', receiptFooter:'', operators:[{id:'a',name:'Ana',username:'Ana',active:true,passwordDigest:'pbkdf2$210000$f0b1c2d3e4a5968778695a4b3c2d1e0f$b84de8daef4e4446728eae9b4538c581263a0016be025069784688ab3df51d56'},{id:'b',name:'Bruno',username:'Bruno',active:true,passwordDigest:'pbkdf2$210000$f0b1c2d3e4a5968778695a4b3c2d1e0f$b84de8daef4e4446728eae9b4538c581263a0016be025069784688ab3df51d56'}] }));
   localStorage.setItem('raiz-pdv:cash', JSON.stringify({sessions:[{id:'yesterday',openedAt:yesterday,openingAmountInCents:10000,status:'open',operatorId:'a',operatorName:'Ana'}],movements:[]}));
   localStorage.setItem('raiz-pdv:completed-sales', JSON.stringify([{id:'old-sale',number:1,date:yesterday,cashSessionId:'yesterday',status:'completed',items:[{productId:'p',productName:'Produto',unitPriceInCents:2500,quantity:1,subtotalInCents:2500}],totalInCents:2500,payments:[{method:'pix',amountInCents:2500}]}]));
   localStorage.setItem('operator-test-seeded','yes');
  });
  await page.goto('http://127.0.0.1:5173/');
  const login = async (username,password='123456') => {
   await page.getByRole('textbox',{name:'Operador',exact:true}).fill(username);
   await page.getByLabel('Senha',{exact:true}).fill(password);
   await page.getByRole('button',{name:'Entrar',exact:true}).click();
   await page.getByRole('button',{name:'Sair / trocar operador',exact:true}).waitFor();
  };
  await page.getByRole('textbox',{name:'Operador',exact:true}).fill('Ana');
  await page.getByLabel('Senha',{exact:true}).fill('errada');
  await page.getByRole('button',{name:'Entrar',exact:true}).click();
  await page.getByText('Operador ou senha incorretos.',{exact:true}).waitFor();
  await login('Ana');
  await page.getByRole('button',{name:'＋ Abrir caixa',exact:true}).click();
  assert.equal(await page.locator('.cash-field select').isDisabled(),true);
  await page.locator('#cash-amount').fill('0');
  await page.getByRole('button',{name:'Abrir caixa',exact:true}).click();
  await page.locator('.cash-modal .cash-error').filter({hasText:'pendente'}).waitFor();
  await page.keyboard.press('Escape');
  await page.getByRole('button',{name:'Sair / trocar operador',exact:true}).click();
  await login('Bruno');
  await page.getByRole('button',{name:'＋ Abrir caixa',exact:true}).click();
  await page.locator('#cash-amount').fill('0');
  await page.getByRole('button',{name:'Abrir caixa',exact:true}).click();
  await page.locator('.cash-status').filter({hasText:'Bruno'}).waitFor();
  assert.match(await page.locator('.cash-net-sales').innerText(), /0,00[\s\S]*0 venda/);
  assert.equal(await page.locator('.cash-pending-row').count(),1);
  await page.getByRole('button',{name:'Nova venda',exact:true}).click();
  await page.locator('.open-pill').filter({hasText:'Bruno'}).waitFor();
  await page.getByRole('button',{name:'Caixa',exact:true}).click();
  await page.getByRole('button',{name:'Configurações',exact:true}).click();
  await page.getByRole('heading',{name:'Acesso do administrador',exact:true}).waitFor();
  await page.getByRole('button',{name:'Sair / trocar operador',exact:true}).click();
  await login('Admin');
  await page.getByRole('button',{name:'Fechar caixa pendente',exact:true}).click();
  await page.locator('#count-cash').fill('100'); await page.locator('#count-pix').fill('25'); await page.locator('#count-debit').fill('0'); await page.locator('#count-credit').fill('0');
  await page.getByRole('button',{name:/Revisar/}).click();
  await page.getByRole('button',{name:/Confirmar fechamento/}).click();
  await page.locator('.cash-pending-row').waitFor({state:'detached'});
  assert.match(await page.locator('.cash-status').innerText(), /Bruno/);
  const records = await page.evaluate(() => JSON.parse(localStorage.getItem('raiz-pdv:cash')));
  assert.equal(records.sessions.find(item=>item.id==='yesterday').status,'closed');
  assert.ok(records.sessions.find(item=>item.id==='yesterday').closedAt);
  assert.equal(records.sessions.find(item=>item.operatorId==='b').status,'open');
  await page.getByRole('button',{name:'Configurações',exact:true}).click();
  await page.getByRole('textbox',{name:'Nome do operador',exact:true}).fill('Carla');
  await page.getByRole('textbox',{name:'Usuário do operador',exact:true}).fill('Carla');
  await page.getByRole('button',{name:'Adicionar operador',exact:true}).click();
  await page.getByLabel('Senha de Carla',{exact:true}).fill('654321');
  await page.getByRole('button',{name:'Salvar alterações',exact:true}).click();
  await page.waitForFunction(()=>JSON.parse(localStorage.getItem('raiz-pdv:settings')).operators.length===4);
  await page.getByLabel('Senha de Admin',{exact:true}).fill('admin789');
  await page.getByRole('button',{name:'Salvar alterações',exact:true}).click();
  await page.getByRole('heading',{name:'Entrar no Raiz PDV',exact:true}).waitFor();
  await login('Admin','admin789');
  await page.getByRole('button',{name:'Sair / trocar operador',exact:true}).click();
  await login('Carla','654321');
  console.log('PASS: pendência bloqueia Ana, Bruno abre hoje, totais separados, fechamento da pendência preserva caixa atual, cadastro salva operador.');
 } finally { await browser.close(); }
})().catch(error=>{console.error(error);process.exitCode=1;});
