const {test}=require('node:test');const assert=require('node:assert/strict');const {Worker}=require('node:worker_threads');const {resolve}=require('node:path');const {fixture}=require('./helpers/sqlite-backend.cjs');
function worker(t,data){const instance=new Worker(resolve('tests/helpers/sqlite-worker.cjs'),{workerData:data});t.after(()=>instance.terminate());let complete,lastResult;const result=new Promise((resolve,reject)=>{complete=resolve;instance.on('error',reject);});const ready=new Promise((resolve,reject)=>{instance.on('error',reject);instance.on('message',message=>{if(message.ready)resolve();else{lastResult=message;resolve();}});});instance.once('exit',()=>complete(lastResult));return {ready,result,start:()=>instance.postMessage('go')};}
async function race(t,f,kind,inputs,extra={}){const workers=inputs.map(input=>worker(t,{profile:f.profile,kind,input,...extra}));await Promise.all(workers.map(w=>w.ready));workers.forEach(w=>w.start());return Promise.all(workers.map(w=>w.result));}
function saleInput(f,id='same'){return {requestId:id,items:[{productId:f.product.id,quantity:1,unitPriceInCents:1000}],totalInCents:1000,payments:[{method:'pix',amountInCents:1000}],cashSessionId:f.session.id};}
test('duas conexões completam a mesma venda com um único efeito e mesma resposta',async t=>{const f=fixture(t);const results=await race(t,f,'sales.complete',[saleInput(f),saleInput(f)]);assert.ok(results.every(r=>r.ok));assert.equal(results[0].value.id,results[1].value.id);assert.equal(f.database.read('SELECT count(*) AS n FROM sales')[0].n,1);assert.equal(f.database.read('SELECT next_number FROM sale_sequence')[0].next_number,2);});
test('duas vendas disputando o mesmo crédito respeitam reserva/saldo',async t=>{const f=fixture(t),issued=f.issue(1),payments=[{method:'customer_credit',amountInCents:1000,customerCreditId:issued.credit.id}];const results=await race(t,f,'sales.complete',[{...saleInput(f,'a'),payments},{...saleInput(f,'b'),payments}],{credit:{query:issued.credit.receiptNumber,code:issued.code}});assert.equal(results.filter(r=>r.ok).length,1);assert.equal(results.find(r=>!r.ok).code,'INSUFFICIENT_FUNDS');assert.equal(f.database.read('SELECT balance_cents FROM customer_credits')[0].balance_cents,0);assert.equal(f.database.read("SELECT count(*) AS n FROM customer_credit_movements WHERE type='redeemed'")[0].n,1);});
test('cancelamento simultâneo não repete histórico nem restauração',async t=>{const f=fixture(t),sale=f.complete();const input={requestId:'cancel-race',id:sale.id,reason:'customer_cancelled'};const results=await race(t,f,'sales.cancel',[input,input]);assert.ok(results.every(r=>r.ok));assert.equal(f.database.read('SELECT count(*) AS n FROM sale_cancellations')[0].n,1);});
test('conclusão concorrente de reembolso é idempotente',async t=>{const f=fixture(t),sale=f.complete();f.call('sales.cancel',{requestId:'cancel',id:sale.id,reason:'customer_cancelled'});const result=f.call('financial.settle',{requestId:'refund',saleId:sale.id,amounts:f.amounts('pix',1000),statuses:{pix:'pending'},cashSessionId:f.session.id});const input={requestId:'refund-race',id:result.refunds[0].id,status:'completed',cashSessionId:f.session.id};const results=await race(t,f,'financial.updateRefund',[input,input]);assert.ok(results.every(r=>r.ok));assert.equal(f.database.read("SELECT count(*) AS n FROM financial_refunds WHERE status='completed'")[0].n,1);});
test('fechamento simultâneo mantém um único snapshot',async t=>{const f=fixture(t);const fingerprint=JSON.stringify({session:{id:f.session.id,status:'open',openedAt:f.session.openedAt,openingAmountInCents:10000},movements:[],financial:{refunds:[],returns:[]},sales:[]});const input={requestId:'close-race',sessionId:f.session.id,counts:{cash:10000,pix:0,debit:0,credit:0},reviewedFingerprint:fingerprint};const results=await race(t,f,'cash.close',[input,input]);assert.ok(results.every(r=>r.ok));assert.equal(f.database.read('SELECT count(*) AS n FROM cash_reconciliation_snapshots')[0].n,1);});
test('SQLITE_BUSY na execução não cria request nem efeito; reenvio explícito confirma',async t=>{const f=fixture(t),input=saleInput(f,'busy'),w=worker(t,{profile:f.profile,kind:'sales.complete',input,busyTimeoutMs:0});await w.ready;f.database.transaction(()=>{w.start();Atomics.wait(new Int32Array(new SharedArrayBuffer(4)),0,0,500);});const result=await w.result;assert.equal(result.code,'DATABASE_BUSY');assert.equal(f.database.read("SELECT count(*) AS n FROM operation_requests WHERE request_id='busy'")[0].n,0);const sale=f.call('sales.complete',input);assert.equal(sale.number,1);});
