import {randomUUID} from 'node:crypto';
import {existsSync,readFileSync,mkdirSync,renameSync,lstatSync,copyFileSync} from 'node:fs';
import {join,dirname,basename} from 'node:path';
import {SqliteFoundation} from './database.cjs';
import {OperationalBackend} from './backend.cjs';
import {DatabaseFailure} from './errors.cjs';
import {credential} from './auth.cjs';
import {databasePath} from './profile.cjs';
import type {DatabaseMode} from './profile.cjs';
import {createNativeBackup,validateRecovered,logicalHash,durable,sha} from './native-backup.cjs';
import type {BackupProof} from './native-backup.cjs';
import {inspectWeb,importWeb} from './web-import.cjs';
import {INITIAL_SCHEMA} from './schema.cjs';
import type {StoreSettings} from '../../../src/types/settings';
function fail(code:ConstructorParameters<typeof DatabaseFailure>[0]):never{throw new DatabaseFailure(code);}
function readArchive(path:string){try{const stat=lstatSync(path);if(!stat.isFile()||stat.isSymbolicLink()||stat.size>512*1024*1024)fail('BACKUP_INVALID');return readFileSync(path,'utf8');}catch(error){if(error instanceof DatabaseFailure)throw error;return fail('BACKUP_INVALID');}}
export const resetTables=['native_drafts','legacy_records','cash_reconciliation_methods','cash_reconciliation_snapshots','customer_credit_reservations','recovery_events','backup_imports','sale_payments','customer_credit_movements','financial_refunds','customer_credits','merchandise_return_items','merchandise_returns','sale_cancellations','sale_items','sales','cash_movements','cash_sessions','products','product_images','categories','operation_requests','operator_credentials','operators','store_settings'] as const;
export function recoverReplacement(profile:string,mode:DatabaseMode){const path=databasePath(profile,mode),journal=path+'.replacement.json';if(!existsSync(journal))return;try{const j=JSON.parse(readFileSync(journal,'utf8'));if(!/^raiz-pdv\.sqlite\.previous-[a-f0-9-]+$/.test(j.previous)||!/^raiz-pdv\.sqlite\.candidate-[a-f0-9-]+$/.test(j.candidate))fail('RESTORE_BLOCKED');const previous=join(dirname(path),j.previous),candidate=join(dirname(path),j.candidate);if(!existsSync(path)&&existsSync(previous))renameSync(previous,path);if(!existsSync(path))fail('RESTORE_BLOCKED');try{const db=SqliteFoundation.open({userData:profile,mode});try{db.diagnostics();}finally{db.close();}}catch(error){if(!existsSync(previous))throw error;const checkProfile=join(dirname(path),'recovery-check-'+randomUUID()),checkPath=databasePath(checkProfile,'test');mkdirSync(dirname(checkPath),{recursive:true});copyFileSync(previous,checkPath);const check=SqliteFoundation.open({userData:checkProfile,mode:'test'});try{check.diagnostics();}finally{check.close();}renameSync(path,path+'.failed-'+randomUUID());renameSync(previous,path);const recovered=SqliteFoundation.open({userData:profile,mode});try{recovered.transaction(tx=>tx.run('INSERT INTO installation_audit VALUES(?,?,?,?,?)',randomUUID(),'restore_rollback',recovered.installationState().generation,new Date().toISOString(),'{}'));recovered.diagnostics();}finally{recovered.close();}}renameSync(journal,journal+'.recovered-'+randomUUID());if(existsSync(candidate))renameSync(candidate,candidate+'.preserved');}catch{fail('RESTORE_BLOCKED');}}
export class LifecycleCoordinator {
 private busy=false;
 private proofs=new Map<string,{owner:number;proof:BackupProof;path:string;fingerprint:string;generation:number}>();
 private previews=new Map<string,{owner:number;preview:ReturnType<typeof inspectWeb>;generation:number}>();
 constructor(public backend:OperationalBackend,readonly profile:string,readonly mode:DatabaseMode,private replace:(backend:OperationalBackend)=>void=()=>{},private readonly faultProbe?:(operation:string,phase:string)=>void){}
 status(){const db=this.backend.database,s=db.installationState();if(s.status==='production'&&(!db.read("SELECT o.id FROM operators o JOIN operator_credentials c ON c.operator_id=o.id WHERE o.role='admin' AND o.active=1 LIMIT 1").length||!String(db.read('SELECT store_name FROM store_settings WHERE id=1')[0]?.store_name??'').trim()))fail('INSTALLATION_BLOCKED');return {status:s.status,generation:s.generation,needsSetup:!db.read("SELECT o.id FROM operators o JOIN operator_credentials c ON c.operator_id=o.id WHERE o.role='admin' AND o.active=1 LIMIT 1").length||!db.read('SELECT store_name FROM store_settings WHERE id=1')[0]?.store_name,installationId:s.installation_id!,...(s.status==='testing'?{testDataSummary:{products:Number(db.read('SELECT count(*) AS n FROM products')[0].n),operators:Number(db.read('SELECT count(*) AS n FROM operators')[0].n),sales:Number(db.read('SELECT count(*) AS n FROM sales')[0].n),cashSessions:Number(db.read('SELECT count(*) AS n FROM cash_sessions')[0].n),credits:Number(db.read('SELECT count(*) AS n FROM customer_credits')[0].n),revenue:Number(db.read("SELECT coalesce(sum(total_cents),0) AS n FROM sales WHERE status<>'cancelled'")[0].n),balances:Number(db.read('SELECT coalesce(sum(balance_cents),0) AS n FROM customer_credits')[0].n)}}:{})};}
 private admin(owner:number){return this.backend.database.transaction(db=>this.backend.auth.authorize(db,owner,{admin:true,recent:true}).operator);}
 private authorizeOrNew(owner:number){if(this.backend.database.read('SELECT id FROM operators LIMIT 1').length)this.admin(owner);}
 private async exclusive<T>(work:()=>Promise<T>|T){if(this.busy)fail('DATABASE_BUSY');this.busy=true;this.backend.setMaintenance(true);try{return await work();}finally{this.backend.setMaintenance(false);this.busy=false;}}
 setup(_owner:number,i:{settings:StoreSettings;username:string;name:string;password:string;confirmation:string;mode:'testing'|'production';confirmed:boolean}){
  if(this.busy)fail('DATABASE_BUSY');if(!i.confirmed||i.password!==i.confirmation||i.password.length<6||i.password.length>128||!i.settings.storeName.trim()||!i.username.trim()||!i.name.trim())fail('INVALID_REQUEST');
  const db=this.backend.database,state=db.installationState();if(state.status==='production')fail('FORBIDDEN');if(db.read('SELECT id FROM operators LIMIT 1').length&&!(state.status==='ready_for_setup'&&db.read("SELECT id FROM backup_imports WHERE status='completed' LIMIT 1").length))fail('IMPORT_CONFLICT');if(db.read("SELECT o.id FROM operators o JOIN operator_credentials c ON c.operator_id=o.id WHERE o.role='admin' AND o.active=1 LIMIT 1").length)fail('IMPORT_CONFLICT');if(state.status==='ready_for_setup'&&i.mode!=='production')fail('FORBIDDEN');
  const id=randomUUID(),c=credential(i.password);db.transaction(tx=>{if(tx.get("SELECT o.id FROM operators o JOIN operator_credentials c ON c.operator_id=o.id WHERE o.role='admin' AND o.active=1 LIMIT 1"))fail('IMPORT_CONFLICT');tx.run("INSERT INTO operators VALUES(?,?,?,?,'admin',1)",id,i.name.trim(),i.username.trim(),i.username.trim().toLocaleLowerCase('pt-BR'));tx.run("INSERT INTO operator_credentials VALUES(?,'PBKDF2-SHA256',?,?,?,?)",id,'{"iterations":210000,"length":32}',c.salt,c.verifier,new Date().toISOString());tx.run("INSERT INTO store_settings VALUES(?,?,?,?,?,1,'{}') ON CONFLICT(id) DO UPDATE SET store_name=excluded.store_name,address=excluded.address,phone=excluded.phone,receipt_footer=excluded.receipt_footer",1,i.settings.storeName.trim(),i.settings.address,i.settings.phone,i.settings.receiptFooter);if(state.status==='ready_for_setup')this.backend.recoverForInitialSetup(tx,{id,name:i.name.trim(),username:i.username.trim(),role:'admin',active:true});tx.run('UPDATE installation_state SET status=?,activated_at=? WHERE id=1',i.mode,i.mode==='production'?new Date().toISOString():null);tx.run('INSERT INTO installation_audit VALUES(?,?,?,?,?)',randomUUID(),'setup',state.generation,new Date().toISOString(),JSON.stringify({mode:i.mode}));this.faultProbe?.('setup','before_commit');});this.faultProbe?.('setup','after_commit');this.backend.invalidateAll();return this.status();
 }
 activate(owner:number,confirmed:boolean){this.admin(owner);if(!confirmed)fail('CONFIRMATION_REQUIRED');const recoveryId=this.backend.execute(owner,'operations.prepare',{kind:'financial.recover',payload:{}}).requestId;this.backend.execute(owner,'financial.recover',{requestId:recoveryId});this.backend.execute(owner,'operations.acknowledge',{requestId:recoveryId});this.backend.checkLedger();this.backend.database.transaction(tx=>{const s=this.backend.database.installationState();if(s.status!=='ready_for_setup'||!tx.get("SELECT o.id FROM operators o JOIN operator_credentials c ON c.operator_id=o.id WHERE o.active=1 AND o.role='admin'")||!String(tx.get('SELECT store_name FROM store_settings WHERE id=1')?.store_name??'').trim())fail('INSTALLATION_BLOCKED');tx.run("UPDATE installation_state SET status='production',activated_at=? WHERE id=1",new Date().toISOString());tx.run('INSERT INTO installation_audit VALUES(?,?,?,?,?)',randomUUID(),'activate',s.generation,new Date().toISOString(),'{}');});return this.status();}
 async backup(owner:number,destination:string,secret:string,overwrite=false){this.authorizeOrNew(owner);return this.exclusive(async()=>{const db=this.backend.database,proof=await createNativeBackup(db,this.backend.custody??fail('UNSUPPORTED_OPERATION'),destination,this.profile,secret,overwrite);if(logicalHash(db)!==proof.logicalHash)fail('BACKUP_STALE');const id=randomUUID();this.proofs.set(id,{owner,proof,path:destination,fingerprint:proof.logicalHash,generation:proof.generation});return {proofId:id,...proof};});}
 async verify(owner:number,path:string,secret:string){this.authorizeOrNew(owner);return this.exclusive(()=>{if(!lstatSync(path).isFile()||lstatSync(path).isSymbolicLink()||lstatSync(path).size>512*1024*1024)fail('BACKUP_INVALID');return validateRecovered(readArchive(path),secret,this.backend.custody??fail('UNSUPPORTED_OPERATION')).manifest;});}
 preview(owner:number,contents:string){if(this.busy)fail('DATABASE_BUSY');this.authorizeOrNew(owner);const db=this.backend.database;if(db.read('SELECT id FROM sales LIMIT 1').length||db.read('SELECT id FROM products LIMIT 1').length||db.read('SELECT id FROM operators LIMIT 1').length)fail('IMPORT_CONFLICT');const preview=inspectWeb(contents),id=randomUUID();this.previews.set(id,{owner,preview,generation:db.installationState().generation});return {previewId:id,summary:preview.summary,metrics:preview.metrics,warnings:preview.warnings};}
 async import(owner:number,previewId:string,proofId:string,confirmed:boolean,secret:string){this.authorizeOrNew(owner);if(!confirmed)fail('CONFIRMATION_REQUIRED');const candidate=this.previews.get(previewId);if(!candidate||candidate.owner!==owner)fail('IMPORT_INVALID');return this.exclusive(()=>{const db=this.backend.database,proof=this.requireProof(owner,proofId,secret);const state=db.installationState();if(state.status==='production'||candidate.generation!==state.generation)fail('FORBIDDEN');const result=db.transaction(tx=>{const result=importWeb(tx,candidate.preview.data,state.generation,randomUUID(),sha(proof.path),candidate.preview.version,candidate.preview.digest);tx.run("UPDATE installation_state SET status='ready_for_setup',activated_at=NULL WHERE id=1");this.faultProbe?.('import','before_commit');return result;});this.faultProbe?.('import','after_commit');this.previews.delete(previewId);this.backend.invalidateAll();return {metrics:result,warnings:candidate.preview.warnings};});}
 private requireProof(owner:number,id:string,secret:string){const p=this.proofs.get(id),db=this.backend.database;if(!p||p.owner!==owner||p.generation!==db.installationState().generation)fail('BACKUP_REQUIRED');const verified=validateRecovered(readArchive(p.path),secret,this.backend.custody??fail('UNSUPPORTED_OPERATION')).manifest;if(verified.databaseHash!==p.proof.databaseHash||logicalHash(db)!==p.fingerprint)fail('BACKUP_STALE');return p;}
 async prepare(owner:number,i:{proofId:string;secret:string;first:boolean;second:boolean;phrase:string}){this.admin(owner);if(!i.first||!i.second||i.phrase!=='ZERAR RAIZ PDV')fail('CONFIRMATION_REQUIRED');if(this.backend.database.installationState().status!=='testing')fail('FORBIDDEN');return this.exclusive(()=>{const db=this.backend.database;this.requireProof(owner,i.proofId,i.secret);db.transaction(tx=>{this.backend.auth.authorize(tx,owner,{admin:true,recent:true});const state=db.installationState();if(state.status!=='testing'||!Number.isSafeInteger(state.generation+1))fail('FORBIDDEN');if(tx.get("SELECT request_id FROM operation_requests WHERE status='pending'"))fail('REQUEST_INTERRUPTED');
 const triggerSql=INITIAL_SCHEMA.split('\n').filter(sql=>sql.startsWith('CREATE TRIGGER '));for(const t of ['cash_reconciliation_snapshots','cash_reconciliation_methods'])for(const action of ['update','delete'])tx.run('DROP TRIGGER '+t+'_immutable_'+action);
 // Deferred cycle is explicitly broken inside the exclusive transaction; every row is then removed.
 tx.run("UPDATE financial_refunds SET credit_id=NULL,method=CASE WHEN method='customer_credit' THEN 'pix' ELSE method END WHERE credit_id IS NOT NULL");
 for(const table of resetTables)tx.run('DELETE FROM '+table);for(const sql of triggerSql)tx.run(sql);tx.run('UPDATE sale_sequence SET next_number=1 WHERE id=1');tx.run("UPDATE installation_state SET generation=?,status='ready_for_setup',activated_at=NULL WHERE id=1",state.generation+1);tx.run('INSERT INTO installation_audit VALUES(?,?,?,?,?)',randomUUID(),'prepare_for_official_use',state.generation+1,new Date().toISOString(),JSON.stringify({previousGeneration:state.generation,backupHash:this.proofs.get(i.proofId)!.proof.databaseHash}));this.faultProbe?.('prepare','before_commit');});this.faultProbe?.('prepare','after_commit');this.backend.invalidateAll();this.proofs.clear();this.previews.clear();db.diagnostics();return this.status();});}
 async restore(owner:number,path:string,secret:string,proofId:string,confirmed:boolean){this.admin(owner);if(!confirmed)fail('CONFIRMATION_REQUIRED');return this.exclusive(()=>{const old=this.backend,db=old.database;const safety=this.requireProof(owner,proofId,secret);const archive=validateRecovered(readArchive(path),secret,old.custody??fail('UNSUPPORTED_OPERATION'));const state=db.installationState();if(archive.manifest.installationId===state.installation_id&&archive.manifest.generation>state.generation||state.status==='production'&&archive.manifest.status!=='production')fail('RESTORE_BLOCKED');if(archive.manifest.installationId!==state.installation_id&&['sales','products','cash_sessions','customer_credits','backup_imports'].some(table=>db.read('SELECT id FROM '+table+' LIMIT 1').length))fail('RESTORE_BLOCKED');
 const target=databasePath(this.profile,this.mode),candidate=target+'.candidate-'+randomUUID(),previous=target+'.previous-'+randomUUID(),journal=target+'.replacement.json';if(existsSync(journal))fail('RESTORE_BLOCKED');const stageProfile=join(dirname(target),'restore-stage-'+randomUUID());const stagePath=databasePath(stageProfile,'test');mkdirSync(dirname(stagePath),{recursive:true});durable(stagePath,archive.bytes);const restored=SqliteFoundation.open({userData:stageProfile,mode:'test'});try{restored.transaction(tx=>{for(const [id,code]of Object.entries(archive.codes))tx.run('UPDATE customer_credits SET receipt_ciphertext=? WHERE id=?',old.custody!.seal(code),id);tx.run('UPDATE installation_state SET installation_id=?,generation=?,status=?,activated_at=? WHERE id=1',archive.manifest.installationId,Math.max(state.generation,archive.manifest.generation)+1,state.status==='production'?'production':archive.manifest.status,state.status==='production'?state.activated_at:archive.manifest.status==='production'?new Date().toISOString():null);tx.run('DELETE FROM native_drafts');tx.run('INSERT INTO installation_audit VALUES(?,?,?,?,?)',randomUUID(),'restore',Math.max(state.generation,archive.manifest.generation)+1,new Date().toISOString(),JSON.stringify({sourceHash:archive.manifest.databaseHash,safetyHash:safety.proof.databaseHash}));});restored.diagnostics();}finally{restored.close();}
 renameSync(stagePath,candidate);durable(journal,JSON.stringify({previous:basename(previous),candidate:basename(candidate)}));this.faultProbe?.('restore','candidate_ready');db.closeForReplacement(()=>{if(logicalHash(db)!==safety.fingerprint)fail('BACKUP_STALE');});old.invalidateAll();renameSync(target,previous);this.faultProbe?.('restore','previous_preserved');renameSync(candidate,target);this.faultProbe?.('restore','new_installed');
 try{const next=SqliteFoundation.open({userData:this.profile,mode:this.mode});this.backend=new OperationalBackend(next,Date.now,old.custody);this.replace(this.backend);renameSync(journal,journal+'.completed-'+randomUUID());this.proofs.clear();this.previews.clear();return this.status();}catch{recoverReplacement(this.profile,this.mode);throw new DatabaseFailure('RESTORE_BLOCKED');}
 });}
}
