import {validateFinancialRelations} from '../../../src/services/backupStorage';
import * as read from './read-model.cjs';
import {createHash,randomBytes,randomUUID,scryptSync,createCipheriv,createDecipheriv} from 'node:crypto';
import {readFileSync,writeFileSync,mkdirSync,mkdtempSync,lstatSync,existsSync,renameSync,openSync,fsyncSync,closeSync,rmSync,realpathSync,linkSync,unlinkSync} from 'node:fs';
import {join,dirname,resolve,relative,isAbsolute,sep} from 'node:path';
import {tmpdir} from 'node:os';
import {SqliteFoundation} from './database.cjs';
import {OperationalBackend} from './backend.cjs';
import {databasePath} from './profile.cjs';
import {DatabaseFailure} from './errors.cjs';
import {creditVerifier} from './auth.cjs';
const max=512*1024*1024;
export function logicalHash(db:SqliteFoundation){const hash=createHash('sha256');for(const {name}of db.read("SELECT name FROM sqlite_schema WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name")){hash.update(String(name));hash.update(JSON.stringify(db.read('SELECT * FROM "'+String(name).replaceAll('"','""')+'" ORDER BY rowid')));}return hash.digest('hex');}
export const sha=(data:string|Uint8Array)=>createHash('sha256').update(data).digest('hex');
export type BackupProof={created:true;verified:true;recoverable:true;portableCodes:number;legacyCodes:number;schemaVersion:number;generation:number;status:string;installationId:string;databaseHash:string;logicalHash:string};
type Envelope={format:'raiz-pdv-sqlite-backup';version:1;manifest:BackupProof & {exportedAt:string};kdf:{algorithm:'scrypt';N:32768;r:8;p:1;salt:string};iv:string;tag:string;ciphertext:string;hash:string};
function key(secret:string,salt:Buffer){if(secret.length<12||secret.length>128)throw new DatabaseFailure('BACKUP_SECRET_INVALID');return scryptSync(secret,salt,32,{N:32768,r:8,p:1,maxmem:64*1024*1024});}
function durable(path:string,data:string|Uint8Array){const fd=openSync(path,'wx',0o600);try{writeFileSync(fd,data);fsyncSync(fd);}finally{closeSync(fd);}}
export function checkedExternal(path:string,profile:string){const parent=realpathSync(dirname(resolve(path))),root=realpathSync(profile);const rel=relative(root,parent);if(!rel||(!rel.startsWith('..'+sep)&&rel!=='..'&&!isAbsolute(rel))||existsSync(path)&&(!lstatSync(path).isFile()||lstatSync(path).isSymbolicLink()))throw new DatabaseFailure('BACKUP_DESTINATION_INVALID');return join(parent,resolve(path).split(/[\\/]/).pop()!);}
function temp(){const root=realpathSync(tmpdir()),profile=mkdtempSync(join(root,'raiz-backup-check-'));return {profile,remove:()=>{if(!resolve(profile).startsWith(root+sep))throw new DatabaseFailure('BACKUP_INVALID');rmSync(profile,{recursive:true,force:true});}};}
export function decodeArchive(contents:string,secret:string){
 try{if(Buffer.byteLength(contents)>max)throw 0;const e=JSON.parse(contents) as Envelope;if(e.format!=='raiz-pdv-sqlite-backup'||e.version!==1||e.kdf.algorithm!=='scrypt'||e.kdf.N!==32768||e.kdf.r!==8||e.kdf.p!==1||!/^([a-f0-9]{32})$/.test(e.kdf.salt)||!/^([a-f0-9]{24})$/.test(e.iv)||!/^([a-f0-9]{32})$/.test(e.tag)||e.hash!==sha(Buffer.from(e.ciphertext,'base64')))throw 0;const k=key(secret,Buffer.from(e.kdf.salt,'hex'));try{const cipher=createDecipheriv('aes-256-gcm',k,Buffer.from(e.iv,'hex'));cipher.setAAD(Buffer.from(JSON.stringify(e.manifest)));cipher.setAuthTag(Buffer.from(e.tag,'hex'));const payload=JSON.parse(Buffer.concat([cipher.update(Buffer.from(e.ciphertext,'base64')),cipher.final()]).toString('utf8')) as {database:string;codes:Record<string,string>};const bytes=Buffer.from(payload.database,'base64');if(bytes.length>max||sha(bytes)!==e.manifest.databaseHash||!payload.codes||typeof payload.codes!=='object'||Array.isArray(payload.codes))throw 0;return {bytes,codes:payload.codes,manifest:e.manifest};}finally{k.fill(0);}
 }catch(error){if(error instanceof DatabaseFailure&&error.code==='BACKUP_SECRET_INVALID')throw error;throw new DatabaseFailure('BACKUP_INVALID');}
}
export function validateRecovered(contents:string,secret:string,vault:NonNullable<OperationalBackend['custody']>){const decoded=decodeArchive(contents,secret),t=temp();let db:SqliteFoundation|undefined;try{const path=databasePath(t.profile,'test');mkdirSync(dirname(path),{recursive:true});durable(path,decoded.bytes);db=SqliteFoundation.open({userData:t.profile,mode:'test'});db.transaction(tx=>{validateFinancialRelations({products:read.products(tx),settings:read.settings(tx),sales:read.sales(tx),cash:read.cash(tx),financial:read.financial(tx)});for(const credit of tx.all('SELECT * FROM customer_credits')){const moved=tx.get("SELECT coalesce(sum(CASE WHEN type='redeemed' THEN amount_cents WHEN type='restored' THEN -amount_cents ELSE 0 END),0) AS n FROM customer_credit_movements WHERE credit_id=?",String(credit.id))!;if(Number(credit.original_cents)-Number(moved.n)!==Number(credit.balance_cents))throw new DatabaseFailure('BACKUP_INVALID');}});const state=db.installationState(),diag=db.diagnostics();if(state.generation!==decoded.manifest.generation||state.status!==decoded.manifest.status||state.installation_id!==decoded.manifest.installationId||diag.schemaVersion!==decoded.manifest.schemaVersion)throw new DatabaseFailure('BACKUP_INVALID');db.transaction(tx=>{for(const [id,code] of Object.entries(decoded.codes)){if(typeof code!=='string'||code.length>200)throw new DatabaseFailure('BACKUP_INVALID');const credit=tx.get('SELECT authorization_verifier FROM customer_credits WHERE id=?',id);if(!credit||credit.authorization_verifier!==creditVerifier(code))throw new DatabaseFailure('BACKUP_INVALID');const sealed=vault.seal(code);if(vault.open(sealed)!==code)throw new DatabaseFailure('BACKUP_INVALID');tx.run('UPDATE customer_credits SET receipt_ciphertext=? WHERE id=?',sealed,id);}
 for(const credit of tx.all('SELECT id FROM customer_credits WHERE receipt_ciphertext IS NOT NULL'))if(!Object.hasOwn(decoded.codes,String(credit.id)))throw new DatabaseFailure('BACKUP_INVALID');});db.diagnostics();return decoded;}finally{db?.close();t.remove();}}
export async function createNativeBackup(db:SqliteFoundation,vault:NonNullable<OperationalBackend['custody']>,destination:string,profile:string,secret:string,overwrite=false):Promise<BackupProof>{
 const path=checkedExternal(destination,profile);if(existsSync(path)&&!overwrite)throw new DatabaseFailure('CONFIRMATION_REQUIRED');const t=temp();let copy:SqliteFoundation|undefined;const output=join(dirname(path),'.raiz-backup-'+randomUUID()+'.tmp');try{
 const snapshot=databasePath(t.profile,'test');mkdirSync(dirname(snapshot),{recursive:true});await db.backupTo(snapshot);if(!existsSync(snapshot)||!lstatSync(snapshot).isFile()||lstatSync(snapshot).size===0)throw new DatabaseFailure('BACKUP_INVALID');copy=SqliteFoundation.open({userData:t.profile,mode:'test'});const diag=copy.diagnostics(),state=copy.installationState();const codes:Record<string,string>=Object.create(null);for(const c of copy.read('SELECT id,receipt_ciphertext,authorization_verifier FROM customer_credits WHERE receipt_ciphertext IS NOT NULL')){const code=vault.open(c.receipt_ciphertext as Uint8Array);if(creditVerifier(code)!==c.authorization_verifier)throw new DatabaseFailure('BACKUP_INVALID');codes[String(c.id)]=code;}const legacy=Number(copy.read('SELECT count(*) AS n FROM customer_credits WHERE receipt_ciphertext IS NULL')[0].n);const logical=logicalHash(copy);copy.close();copy=undefined;const bytes=readFileSync(snapshot);const proof:BackupProof={created:true,verified:true,recoverable:true,portableCodes:Object.keys(codes).length,legacyCodes:legacy,schemaVersion:diag.schemaVersion,generation:state.generation,status:state.status,installationId:state.installation_id!,databaseHash:sha(bytes),logicalHash:logical};const manifest={...proof,exportedAt:new Date().toISOString()};const salt=randomBytes(16),iv=randomBytes(12),k=key(secret,salt);let contents:string;try{const cipher=createCipheriv('aes-256-gcm',k,iv);cipher.setAAD(Buffer.from(JSON.stringify(manifest)));const ciphertext=Buffer.concat([cipher.update(JSON.stringify({database:bytes.toString('base64'),codes}),'utf8'),cipher.final()]);const envelope:Envelope={format:'raiz-pdv-sqlite-backup',version:1,manifest,kdf:{algorithm:'scrypt',N:32768,r:8,p:1,salt:salt.toString('hex')},iv:iv.toString('hex'),tag:cipher.getAuthTag().toString('hex'),ciphertext:ciphertext.toString('base64'),hash:sha(ciphertext)};contents=JSON.stringify(envelope);}finally{k.fill(0);}
 durable(output,contents);validateRecovered(readFileSync(output,'utf8'),secret,vault);
 if(existsSync(path)){if(!overwrite)throw new DatabaseFailure('CONFIRMATION_REQUIRED');renameSync(path,path+'.previous-'+randomUUID());}linkSync(output,path);unlinkSync(output);validateRecovered(readFileSync(path,'utf8'),secret,vault);return proof;
 }catch(error){if(error instanceof DatabaseFailure)throw error;throw new DatabaseFailure('BACKUP_DESTINATION_INVALID');}finally{copy?.close();if(existsSync(output))unlinkSync(output);t.remove();}
}
export {durable};
