/** Immutable migration source: append versions instead of editing published SQL. */
const MAX = '9007199254740991';
const n = (c: string, min=0) => `${c} INTEGER NOT NULL CHECK(${c} BETWEEN ${min} AND ${MAX})`;
const signed = (c: string) => `${c} INTEGER NOT NULL CHECK(${c} BETWEEN -${MAX} AND ${MAX})`;
const time = (c: string, optional=false) => `${c} TEXT ${optional?'':'NOT NULL'} CHECK(${c} IS NULL OR (length(${c})=24 AND ${c} GLOB '????-??-??T??:??:??.???Z' AND julianday(${c}) IS NOT NULL))`;
const fk = (c: string,t: string, optional=true) => `${c} TEXT ${optional?'':'NOT NULL'} REFERENCES ${t}(id) ON DELETE RESTRICT`;
const id = 'id TEXT PRIMARY KEY NOT NULL CHECK(length(id)>0)';
const methods = "'cash','pix','debit','credit'";
const table = (name: string,columns: string) => `CREATE TABLE ${name} (${columns}) STRICT;`;
export const INITIAL_SCHEMA = [
 table('categories',`${id},name TEXT NOT NULL,normalized_name TEXT NOT NULL UNIQUE CHECK(length(normalized_name)>0)`),
 table('product_images',`${id},mime_type TEXT NOT NULL CHECK(mime_type IN ('image/png','image/jpeg','image/webp','image/gif')),data BLOB NOT NULL CHECK(length(data) BETWEEN 1 AND 10485760),content_hash TEXT NOT NULL CHECK(length(content_hash)=64)`),
 table('products',`${id},name TEXT NOT NULL CHECK(length(name)>0),${fk('category_id','categories',false)},${n('price_cents')},active INTEGER NOT NULL CHECK(active IN (0,1)),emoji TEXT,${fk('image_id','product_images')}`),
 table('store_settings',`id INTEGER PRIMARY KEY CHECK(id=1),store_name TEXT NOT NULL,address TEXT NOT NULL,phone TEXT NOT NULL,receipt_footer TEXT NOT NULL,${n('preferences_version',1)},preferences_json TEXT NOT NULL CHECK(json_valid(preferences_json))`),
 table('operators',`${id},name TEXT NOT NULL,username TEXT NOT NULL,normalized_username TEXT NOT NULL UNIQUE CHECK(length(normalized_username)>0),role TEXT NOT NULL CHECK(role IN ('admin','operator')),active INTEGER NOT NULL CHECK(active IN (0,1))`),
 table('operator_credentials',`operator_id TEXT PRIMARY KEY NOT NULL REFERENCES operators(id) ON DELETE RESTRICT,algorithm TEXT NOT NULL CHECK(algorithm='PBKDF2-SHA256'),parameters_json TEXT NOT NULL CHECK(json_valid(parameters_json)),salt TEXT NOT NULL CHECK(length(salt)>0),verifier TEXT NOT NULL CHECK(length(verifier)>0),${time('changed_at')}`),
 table('cash_sessions',`${id},${fk('operator_id','operators')},operator_name_snapshot TEXT,business_date TEXT CHECK(business_date IS NULL OR (business_date GLOB '????-??-??' AND date(business_date)=business_date)),${time('opened_at')},${time('closed_at',true)},${n('opening_cents')},status TEXT NOT NULL CHECK(status IN ('open','closed')),CHECK((status='open' AND closed_at IS NULL) OR (status='closed' AND closed_at IS NOT NULL)),CHECK(closed_at IS NULL OR closed_at>=opened_at)`),
 table('cash_movements',`${id},${fk('cash_session_id','cash_sessions',false)},${fk('operator_id','operators')},type TEXT NOT NULL CHECK(type IN ('supply','withdrawal')),${n('amount_cents',1)},description TEXT,${time('occurred_at')}`),
 table('sale_sequence',`id INTEGER PRIMARY KEY CHECK(id=1),${n('next_number',1)}`),
 table('sales',`${id},${n('number',1)} UNIQUE,${time('occurred_at')},${fk('cash_session_id','cash_sessions')},${fk('operator_id','operators')},status TEXT NOT NULL CHECK(status IN ('completed','cancelled')),${n('total_cents')}`),
 table('sale_items',`sale_id TEXT NOT NULL REFERENCES sales(id) ON DELETE RESTRICT,line_id TEXT NOT NULL CHECK(length(line_id)>0),${n('position')},product_id TEXT NOT NULL,${fk('catalog_product_id','products')},product_name_snapshot TEXT NOT NULL,${n('unit_price_cents')},${n('quantity',1)},${n('subtotal_cents')},PRIMARY KEY(sale_id,line_id),UNIQUE(sale_id,position),CHECK(unit_price_cents<=${MAX}/quantity AND subtotal_cents=unit_price_cents*quantity)`),
 table('sale_payments',`${id},${fk('sale_id','sales',false)},${n('position')},method TEXT NOT NULL CHECK(method IN (${methods},'customer_credit')),${n('amount_cents',1)},${n('received_cents')},${n('change_cents')},${fk('credit_id','customer_credits')},${time('captured_at',true)},UNIQUE(sale_id,position),CHECK((method='customer_credit' AND credit_id IS NOT NULL) OR (method<>'customer_credit' AND credit_id IS NULL)),CHECK((method='cash' AND received_cents>=amount_cents AND change_cents=received_cents-amount_cents) OR (method<>'cash' AND received_cents=amount_cents AND change_cents=0))`),
 table('sale_cancellations',`sale_id TEXT PRIMARY KEY NOT NULL REFERENCES sales(id) ON DELETE RESTRICT,${fk('operator_id','operators')},${time('cancelled_at')},reason TEXT NOT NULL CHECK(reason IN ('launch_error','customer_cancelled','payment_error','other')),note TEXT`),
 table('merchandise_returns',`${id},${fk('sale_id','sales',false)},${n('sale_number_snapshot',1)},${fk('cash_session_id','cash_sessions')},${fk('operator_id','operators')},${time('occurred_at')},${n('amount_cents',1)},UNIQUE(id,sale_id)`),
 table('merchandise_return_items',`return_id TEXT NOT NULL,${n('position')},sale_id TEXT NOT NULL,line_id TEXT NOT NULL,product_id TEXT NOT NULL,product_name_snapshot TEXT NOT NULL,${n('unit_price_cents')},${n('quantity',1)},${n('amount_cents')},PRIMARY KEY(return_id,position),UNIQUE(return_id,line_id),FOREIGN KEY(return_id,sale_id) REFERENCES merchandise_returns(id,sale_id) ON DELETE RESTRICT,FOREIGN KEY(sale_id,line_id) REFERENCES sale_items(sale_id,line_id) ON DELETE RESTRICT,CHECK(unit_price_cents<=${MAX}/quantity AND amount_cents=unit_price_cents*quantity)`),
 table('financial_refunds',`${id},${fk('sale_id','sales',false)},${n('sale_number_snapshot',1)},return_id TEXT,method TEXT NOT NULL CHECK(method IN (${methods},'customer_credit')),${n('amount_cents',1)},status TEXT NOT NULL CHECK(status IN ('pending','completed','failed')),${time('requested_at')},${time('completed_at',true)},${fk('cash_session_id','cash_sessions')},credit_id TEXT REFERENCES customer_credits(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED,FOREIGN KEY(return_id,sale_id) REFERENCES merchandise_returns(id,sale_id) ON DELETE RESTRICT,UNIQUE(id,sale_id),CHECK((status='completed' AND completed_at IS NOT NULL) OR (status<>'completed' AND completed_at IS NULL)),CHECK(completed_at IS NULL OR completed_at>=requested_at),CHECK((method='customer_credit' AND status='completed' AND credit_id IS NOT NULL) OR (method<>'customer_credit' AND credit_id IS NULL))`),
 table('customer_credits',`${id},receipt_number TEXT NOT NULL UNIQUE,${fk('original_sale_id','sales',false)},${n('original_sale_number',1)},${time('issued_at')},${n('original_cents',1)},${n('balance_cents')},status TEXT NOT NULL CHECK(status IN ('available','partial','redeemed','cancelled')),authorization_verifier TEXT NOT NULL CHECK(length(authorization_verifier)=64 AND authorization_verifier NOT GLOB '*[^0-9a-f]*'),${fk('issuing_cash_session_id','cash_sessions')},CHECK(balance_cents<=original_cents),CHECK((status='available' AND balance_cents=original_cents) OR (status='partial' AND balance_cents>0 AND balance_cents<original_cents) OR (status='redeemed' AND balance_cents=0) OR status='cancelled')`),
 table('customer_credit_movements',`${id},${fk('credit_id','customer_credits',false)},type TEXT NOT NULL CHECK(type IN ('issued','redeemed','restored')),${n('amount_cents',1)},${time('occurred_at')},${fk('sale_id','sales')},${fk('refund_id','financial_refunds')},${fk('cash_session_id','cash_sessions')},CHECK(type='issued' OR sale_id IS NOT NULL)`),
 table('operation_requests',`request_id TEXT PRIMARY KEY NOT NULL CHECK(length(request_id) BETWEEN 1 AND 200),kind TEXT NOT NULL CHECK(length(kind) BETWEEN 1 AND 100),status TEXT NOT NULL CHECK(status IN ('pending','committed','interrupted')),payload_hash TEXT NOT NULL CHECK(length(payload_hash)=64),result_json TEXT CHECK(result_json IS NULL OR json_valid(result_json)),result_reference TEXT,${time('created_at')},${time('completed_at',true)},CHECK((status='committed' AND completed_at IS NOT NULL AND result_json IS NOT NULL) OR (status<>'committed' AND completed_at IS NULL AND result_json IS NULL))`),
 table('customer_credit_reservations',`${id},${fk('credit_id','customer_credits',false)},operation_request_id TEXT NOT NULL REFERENCES operation_requests(request_id) ON DELETE RESTRICT,sale_id TEXT NOT NULL CHECK(length(sale_id)>0),${n('amount_cents',1)},${time('created_at')},state TEXT NOT NULL CHECK(state IN ('reserved','consumed','released')),UNIQUE(credit_id,sale_id)`),
 table('recovery_events',`${id},operation_request_id TEXT REFERENCES operation_requests(request_id) ON DELETE RESTRICT,kind TEXT NOT NULL,outcome TEXT NOT NULL CHECK(outcome IN ('detected','recovered','blocked')),${time('occurred_at')},diagnostic_code TEXT NOT NULL CHECK(diagnostic_code NOT GLOB '*[^A-Z0-9_]*' AND length(diagnostic_code)>0)`),
 table('cash_reconciliation_snapshots',`cash_session_id TEXT PRIMARY KEY NOT NULL REFERENCES cash_sessions(id) ON DELETE RESTRICT,summary_version INTEGER CHECK(summary_version IS NULL OR summary_version=2),${n('revenue_cents')},${signed('net_received_cents')},${n('sale_count')},${n('cancelled_count')},${n('credit_used_cents')},${n('opening_cents')},${n('cash_sales_cents')},${n('supplies_cents')},${n('withdrawals_cents')},${n('refunds_cents')},${n('physical_expected_cents')},source_fingerprint TEXT,${time('closed_at')},legacy_snapshot_json TEXT CHECK(legacy_snapshot_json IS NULL OR json_valid(legacy_snapshot_json))`),
 table('cash_reconciliation_methods',`cash_session_id TEXT NOT NULL REFERENCES cash_reconciliation_snapshots(cash_session_id) ON DELETE RESTRICT,method TEXT NOT NULL CHECK(method IN (${methods})),${n('received_cents')},${n('refunded_cents')},${signed('expected_cents')},${n('counted_cents')},${signed('difference_cents')},PRIMARY KEY(cash_session_id,method),CHECK(method<>'cash' OR expected_cents>=0),CHECK(difference_cents=counted_cents-expected_cents)`),
 table('backup_imports',`${id},operation_request_id TEXT NOT NULL UNIQUE REFERENCES operation_requests(request_id) ON DELETE RESTRICT,source_version INTEGER NOT NULL CHECK(source_version IN (1,2)),payload_digest TEXT NOT NULL CHECK(length(payload_digest)=64),${time('started_at')},${time('completed_at',true)},status TEXT NOT NULL CHECK(status IN ('pending','completed','failed')),safety_copy_reference TEXT NOT NULL CHECK(length(safety_copy_reference)>0),diagnostic_code TEXT,CHECK((status='completed' AND completed_at IS NOT NULL) OR (status<>'completed' AND completed_at IS NULL))`),
 table('installation_state',`id INTEGER PRIMARY KEY CHECK(id=1),status TEXT NOT NULL CHECK(status IN ('testing','ready_for_setup','production')),${time('created_at')},${time('activated_at',true)},${n('generation',1)},CHECK((status='production' AND activated_at IS NOT NULL) OR (status<>'production' AND activated_at IS NULL))`),
 'INSERT INTO sale_sequence(id,next_number) VALUES(1,1);',
 "INSERT INTO installation_state(id,status,created_at,generation) VALUES(1,'testing',strftime('%Y-%m-%dT%H:%M:%fZ','now'),1);",
 'CREATE INDEX product_images_hash ON product_images(content_hash);',
 'CREATE INDEX products_catalog ON products(active,category_id,name);',
 'CREATE INDEX operators_active ON operators(active);',
 'CREATE INDEX cash_sessions_status_date ON cash_sessions(status,business_date);',
 "CREATE UNIQUE INDEX cash_open_date ON cash_sessions(business_date) WHERE status='open' AND business_date IS NOT NULL;",
 "CREATE UNIQUE INDEX cash_open_operator ON cash_sessions(operator_id) WHERE status='open' AND operator_id IS NOT NULL;",
 'CREATE INDEX cash_movements_session_date ON cash_movements(cash_session_id,occurred_at);',
 'CREATE INDEX sales_date ON sales(occurred_at);',
 'CREATE INDEX sales_session_date ON sales(cash_session_id,occurred_at);',
 'CREATE INDEX sales_status_date ON sales(status,occurred_at);',
 'CREATE INDEX sale_payments_method ON sale_payments(method,sale_id);',
 'CREATE INDEX sale_payments_credit ON sale_payments(credit_id);',
 'CREATE INDEX returns_sale_date ON merchandise_returns(sale_id,occurred_at);',
 'CREATE INDEX return_items_sale_line ON merchandise_return_items(sale_id,line_id);',
 'CREATE INDEX refunds_sale_status ON financial_refunds(sale_id,status);',
 'CREATE INDEX refunds_session_date ON financial_refunds(cash_session_id,completed_at);',
 'CREATE INDEX refunds_pending_date ON financial_refunds(status,requested_at);',
 'CREATE INDEX credits_original_sale ON customer_credits(original_sale_id);',
 'CREATE INDEX credits_status_date ON customer_credits(status,issued_at);',
 'CREATE INDEX credit_movements_credit_date ON customer_credit_movements(credit_id,occurred_at);',
 'CREATE INDEX credit_movements_sale ON customer_credit_movements(sale_id);',
 "CREATE UNIQUE INDEX credit_issued_once ON customer_credit_movements(credit_id) WHERE type='issued';",
 "CREATE UNIQUE INDEX credit_sale_movement_once ON customer_credit_movements(credit_id,sale_id,type) WHERE type IN ('redeemed','restored');",
 'CREATE INDEX reservations_sale_state ON customer_credit_reservations(sale_id,state);',
 'CREATE INDEX reservations_request ON customer_credit_reservations(operation_request_id);',
 'CREATE INDEX recovery_request ON recovery_events(operation_request_id);',
 'CREATE INDEX requests_status_date ON operation_requests(status,created_at);',
 'CREATE INDEX imports_digest_status ON backup_imports(payload_digest,status);',
 ...['cash_reconciliation_snapshots','cash_reconciliation_methods'].flatMap(t=>[
  `CREATE TRIGGER ${t}_immutable_update BEFORE UPDATE ON ${t} BEGIN SELECT RAISE(ABORT,'IMMUTABLE_SNAPSHOT'); END;`,
  `CREATE TRIGGER ${t}_immutable_delete BEFORE DELETE ON ${t} BEGIN SELECT RAISE(ABORT,'IMMUTABLE_SNAPSHOT'); END;`,
 ]),
].join('\n');
