import {randomUUID,createHash} from 'node:crypto';
import {parseBackupJson} from '../../../src/services/backupStorage';
import type {BackupData} from '../../../src/types/backup';
import type {TransactionContext} from './database.cjs';
import {DatabaseFailure} from './errors.cjs';
import * as read from './read-model.cjs';
import {sumMoney} from '../../../src/utils/money';
import {getSaleLines} from '../../../src/utils/saleLines';
function bad():never{throw new DatabaseFailure('IMPORT_INVALID');}
const instant=(s:string)=>{try{return new Date(s).toISOString();}catch{return bad();}};
export function inspectWeb(contents:string){
 try{const parsed=parseBackupJson(contents);const version=JSON.parse(contents).version as 1|2;const d=parsed.backup.data;
 for(const group of [d.products,d.cash.sessions,d.cash.movements,d.financial.credits,d.financial.refunds,d.financial.returns,d.financial.creditMovements,d.financial.creditReservations])if(new Set(group.map(x=>x.id)).size!==group.length)bad();
 for(const sale of d.sales){if(new Set(getSaleLines(sale).map(x=>x.lineId)).size!==sale.items.length)bad();}
 for(const r of d.financial.returns){const sale=d.sales.find(s=>s.id===r.saleId)!;for(const item of r.items){const candidates=getSaleLines(sale).filter(x=>(!item.lineId||x.lineId===item.lineId)&&x.productId===item.productId&&x.productName===item.productName&&x.unitPriceInCents*item.quantity===item.amountInCents);if(candidates.length!==1)bad();}}
 return {data:d,version,summary:parsed.summary,digest:createHash('sha256').update(contents).digest('hex'),metrics:metrics(d),warnings:[...(!d.settings.operators?.some(o=>o.role==='admin'&&o.active&&o.passwordDigest)?['ADMINISTRATOR_REQUIRED']:[]),...(d.sales.some(s=>s.items.some(i=>!i.lineId))?['LEGACY_LINE_IDS']:[]),...(d.cash.sessions.some(s=>!s.operatorId)?['LEGACY_OPERATOR_ABSENT']:[]),...(d.financial.credits.length?['LEGACY_CREDIT_ORIGINAL_CODE_REQUIRED']:[]),...(d.financial.creditReservations.length?['RESERVATIONS_REQUIRE_RECOVERY']:[])]};
 }catch(error){if(error instanceof DatabaseFailure)throw error;return bad();}
}
export function metrics(d:BackupData){const count=(xs:unknown[])=>xs.length;const f=d.financial;return {products:count(d.products),categories:new Set(d.products.map(p=>p.category.trim().toLocaleLowerCase('pt-BR'))).size,operators:count(d.settings.operators??[]),sales:count(d.sales),items:sumMoney(d.sales.map(s=>s.items.length)),payments:sumMoney(d.sales.map(s=>s.payments.length)),cashSessions:count(d.cash.sessions),cashMovements:count(d.cash.movements),cancellations:count(d.sales.filter(s=>s.status==='cancelled')),returns:count(f.returns),refunds:count(f.refunds),credits:count(f.credits),creditMovements:count(f.creditMovements),reservations:count(f.creditReservations),closures:count(d.cash.sessions.filter(s=>s.reconciliation)),revenue:sumMoney(d.sales.filter(s=>s.status!=='cancelled').map(s=>s.totalInCents)),received:Object.fromEntries(['cash','pix','debit','credit','customer_credit'].map(method=>[method,sumMoney(d.sales.flatMap(s=>s.payments.filter(p=>p.method===method).map(p=>p.amountInCents)))])),refunded:Object.fromEntries(['cash','pix','debit','credit'].map(method=>[method,sumMoney(f.refunds.filter(r=>r.method===method&&r.status==='completed').map(r=>r.amountInCents))])),issued:sumMoney(f.credits.map(c=>c.originalAmountInCents)),consumed:sumMoney(f.creditMovements.filter(m=>m.type==='redeemed').map(m=>m.amountInCents)),restored:sumMoney(f.creditMovements.filter(m=>m.type==='restored').map(m=>m.amountInCents)),balances:sumMoney(f.credits.map(c=>c.balanceInCents)),nextSale:Math.max(0,...d.sales.map(s=>s.number))+1};}
export function importWeb(db:TransactionContext,d:BackupData,generation:number,importId:string,safety:string,version:number,digest:string){
 if(db.get('SELECT id FROM sales LIMIT 1')||db.get('SELECT id FROM products LIMIT 1')||db.get('SELECT id FROM cash_sessions LIMIT 1')||db.get('SELECT id FROM backup_imports LIMIT 1'))throw new DatabaseFailure('IMPORT_CONFLICT');
 const now=new Date().toISOString(),requestId=randomUUID();db.run("INSERT INTO operation_requests(request_id,kind,status,payload_hash,result_json,created_at,completed_at,generation) VALUES(?,'web_import','committed',?,'{}',?,?,?)",requestId,digest,now,now,generation);
 const original=(kind:string,id:string,value:unknown)=>db.run('INSERT INTO legacy_records VALUES(?,?,?)',kind,id,JSON.stringify(value));
 original('settings','1',d.settings);
 for(const o of d.settings.operators??[]){if(db.get('SELECT id FROM operators WHERE id=? OR normalized_username=?',o.id,(o.username??o.name).trim().toLocaleLowerCase('pt-BR')))throw new DatabaseFailure('IMPORT_CONFLICT');db.run('INSERT INTO operators VALUES(?,?,?,?,?,?)',o.id,o.name,o.username??o.name,(o.username??o.name).trim().toLocaleLowerCase('pt-BR'),o.role??'operator',o.active?1:0);if(o.passwordDigest){const [,iterations,salt,verifier]=o.passwordDigest.split('$');if(iterations!=='210000')bad();db.run("INSERT INTO operator_credentials VALUES(?,'PBKDF2-SHA256',?,?,?,?)",o.id,'{"iterations":210000,"length":32}',salt,verifier,now);}}
 db.run('INSERT INTO store_settings VALUES(?,?,?,?,?,1,?) ON CONFLICT(id) DO UPDATE SET store_name=excluded.store_name,address=excluded.address,phone=excluded.phone,receipt_footer=excluded.receipt_footer,preferences_json=excluded.preferences_json',1,d.settings.storeName,d.settings.address,d.settings.phone,d.settings.receiptFooter,'{}');
 for(const p of d.products){const normalized=p.category.trim().toLocaleLowerCase('pt-BR');let cid=db.get('SELECT id FROM categories WHERE normalized_name=?',normalized)?.id as string|undefined;if(!cid){cid=randomUUID();db.run('INSERT INTO categories VALUES(?,?,?)',cid,p.category,normalized);}let image:string|null=null;if(p.imageDataUrl){const match=/^data:(image\/(?:png|jpeg|webp|gif));base64,([A-Za-z0-9+/]+={0,2})$/.exec(p.imageDataUrl);if(!match)bad();const bytes=Buffer.from(match[2],'base64');if(bytes.toString('base64')!==match[2]||bytes.length>10485760)bad();image=randomUUID();db.run('INSERT INTO product_images VALUES(?,?,?,?)',image,match[1],bytes,createHash('sha256').update(bytes).digest('hex'));}db.run('INSERT INTO products VALUES(?,?,?,?,?,?,?)',p.id,p.name,cid,p.priceInCents,p.active?1:0,p.emoji,image);}
 for(const s of d.cash.sessions){db.run('INSERT INTO cash_sessions VALUES(?,?,?,?,?,?,?,?)',s.id,s.operatorId??null,s.operatorName??null,s.businessDate??null,instant(s.openedAt),s.closedAt?instant(s.closedAt):null,s.openingAmountInCents,s.status);original('cash_session',s.id,s);}
 for(const m of d.cash.movements)db.run('INSERT INTO cash_movements VALUES(?,?,NULL,?,?,?,?)',m.id,m.cashSessionId,m.type,m.amountInCents,m.description??null,instant(m.createdAt));
 for(const s of d.sales){db.run('INSERT INTO sales(id,number,occurred_at,cash_session_id,operator_id,status,total_cents,generation) VALUES(?,?,?,?,NULL,?,?,?)',s.id,s.number,instant(s.date),s.cashSessionId??null,s.status??'completed',s.totalInCents,generation);original('sale',s.id,s);for(const [i,line]of getSaleLines(s).entries())db.run('INSERT INTO sale_items VALUES(?,?,?,?,?,?,?,?,?,?)',s.id,line.lineId,i,line.productId,d.products.some(p=>p.id===line.productId)?line.productId:null,line.productName,line.unitPriceInCents,line.quantity,line.subtotalInCents,s.items[i].lineId?0:1);if(s.status==='cancelled')db.run('INSERT INTO sale_cancellations VALUES(?,NULL,?,?,?)',s.id,instant(s.cancelledAt!),s.cancellationReason!,s.cancellationNote??null);}
 for(const c of d.financial.credits)db.run('INSERT INTO customer_credits(id,receipt_number,original_sale_id,original_sale_number,issued_at,original_cents,balance_cents,status,authorization_verifier,issuing_cash_session_id) VALUES(?,?,?,?,?,?,?,?,?,?)',c.id,c.receiptNumber,c.originalSaleId,c.originalSaleNumber,instant(c.issuedAt),c.originalAmountInCents,c.balanceInCents,c.status,c.authCodeHash!,c.issuingCashSessionId??null);
 for(const s of d.sales)for(const [i,p]of s.payments.entries())db.run('INSERT INTO sale_payments VALUES(?,?,?,?,?,?,?,?,?)',randomUUID(),s.id,i,p.method,p.amountInCents,p.method==='cash'?p.amountReceivedInCents??p.amountInCents:p.amountInCents,p.method==='cash'?p.changeInCents??0:0,p.customerCreditId??null,p.capturedAt?instant(p.capturedAt):null);
 for(const r of d.financial.returns){db.run('INSERT INTO merchandise_returns(id,sale_id,sale_number_snapshot,cash_session_id,operator_id,occurred_at,amount_cents) VALUES(?,?,?,?,NULL,?,?)',r.id,r.saleId,r.saleNumber,r.cashSessionId??null,instant(r.createdAt),r.amountInCents);original('return',r.id,r);const sale=d.sales.find(s=>s.id===r.saleId)!;for(const [i,item]of r.items.entries()){const line=getSaleLines(sale).find(x=>(!item.lineId||x.lineId===item.lineId)&&x.productId===item.productId&&x.productName===item.productName&&x.unitPriceInCents*item.quantity===item.amountInCents)!;db.run('INSERT INTO merchandise_return_items VALUES(?,?,?,?,?,?,?,?,?)',r.id,i,r.saleId,line.lineId,item.productId,item.productName,line.unitPriceInCents,item.quantity,item.amountInCents);}}
 for(const r of d.financial.refunds)db.run('INSERT INTO financial_refunds(id,sale_id,sale_number_snapshot,return_id,method,amount_cents,status,requested_at,completed_at,cash_session_id,credit_id) VALUES(?,?,?,?,?,?,?,?,?,?,?)',r.id,r.saleId,r.saleNumber,r.returnId??null,r.method,r.amountInCents,r.status,instant(r.createdAt),r.completedAt?instant(r.completedAt):null,r.cashSessionId??null,r.creditId??null);
 for(const m of d.financial.creditMovements)db.run('INSERT INTO customer_credit_movements(id,credit_id,type,amount_cents,occurred_at,sale_id,refund_id,cash_session_id) VALUES(?,?,?,?,?,?,?,?)',m.id,m.creditId,m.type,m.amountInCents,instant(m.createdAt),m.saleId??null,m.refundId??null,m.cashSessionId??null);
 for(const r of d.financial.creditReservations){const req=randomUUID();db.run("INSERT INTO operation_requests(request_id,kind,status,payload_hash,created_at,generation) VALUES(?,'legacy_reservation','pending',?,?,?)",req,createHash('sha256').update(r.id).digest('hex'),instant(r.createdAt),generation);db.run("INSERT INTO customer_credit_reservations VALUES(?,?,?,?,?,?,'reserved')",r.id,r.creditId,req,r.saleId,r.amountInCents,instant(r.createdAt));}
 for(const s of d.cash.sessions)if(s.reconciliation){const r=s.reconciliation,c=r.cashSummary;db.run('INSERT INTO cash_reconciliation_snapshots(cash_session_id,summary_version,revenue_cents,net_received_cents,sale_count,cancelled_count,credit_used_cents,opening_cents,cash_sales_cents,supplies_cents,withdrawals_cents,refunds_cents,physical_expected_cents,source_fingerprint,closed_at,legacy_snapshot_json) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',s.id,r.summaryVersion??null,r.totalNetSalesInCents,r.netReceivedInCents??0,r.saleCount??0,r.cancelledCount??0,r.customerCreditConsumedInCents??0,c.openingInCents,c.salesInCents,c.suppliesInCents,c.withdrawalsInCents,c.refundsInCents??0,c.expectedInCents,null,instant(s.closedAt!),JSON.stringify(s));for(const method of ['cash','pix','debit','credit'] as const){const m=r.methods[method];db.run('INSERT INTO cash_reconciliation_methods VALUES(?,?,?,?,?,?,?)',s.id,method,r.paymentTotalsInCents[method],r.refundTotalsInCents?.[method]??0,m.expectedInCents,m.countedInCents,m.differenceInCents);}}
 db.run('UPDATE sale_sequence SET next_number=? WHERE id=1',metrics(d).nextSale);
 const actual:BackupData={products:read.products(db),settings:read.settings(db),sales:read.sales(db),cash:read.cash(db),financial:read.financial(db)};
 if(JSON.stringify(metrics(actual))!==JSON.stringify(metrics(d)))throw new DatabaseFailure('IMPORT_DIVERGENCE');
 db.run("INSERT INTO backup_imports VALUES(?,?,?,?,?,?,'completed',?,NULL)",importId,requestId,version,digest,now,now,safety);
 db.run('INSERT INTO installation_audit VALUES(?,?,?,?,?)',randomUUID(),'web_import',generation,now,JSON.stringify({digest,metrics:metrics(actual)}));return metrics(actual);
}
