const {OperationalBackend,SqliteFoundation}=require('../../dist-electron/main/sqlite/backend.cjs');
const {mkdtempSync,rmSync}=require('node:fs');const {tmpdir}=require('node:os');const {join,resolve,sep}=require('node:path');const {randomBytes,createCipheriv,createDecipheriv}=require('node:crypto');
function vault(key=randomBytes(32)){return {seal(secret){const iv=randomBytes(12),cipher=createCipheriv('aes-256-gcm',key,iv),data=Buffer.concat([cipher.update(secret,'utf8'),cipher.final()]);return Buffer.concat([iv,cipher.getAuthTag(),data]);},open(bytes){const data=Buffer.from(bytes),decipher=createDecipheriv('aes-256-gcm',key,data.subarray(0,12));decipher.setAuthTag(data.subarray(12,28));return Buffer.concat([decipher.update(data.subarray(28)),decipher.final()]).toString('utf8');}};}
function fixture(t,{open=true,configure=true,migrations}={}){const profile=mkdtempSync(join(tmpdir(),'raiz-operational-'));let time=Date.parse('2026-10-09T12:00:00Z'),database,backend;const custody=vault();const create=()=>{database=SqliteFoundation.open({userData:profile,mode:'test',busyTimeoutMs:5000,...(migrations?{migrations}:{})});backend=new OperationalBackend(database,()=>time,custody);};create();t.after(()=>{database.close();const target=resolve(profile);if(!target.startsWith(resolve(tmpdir())+sep))throw Error('UNSAFE_TEST_PATH');rmSync(target,{recursive:true,force:true});});const call=(name,payload={},owner=1)=>backend.execute(owner,name,payload);
let operatorId;if(configure){operatorId=backend.configureInitialAdministrator({username:'Mestre',name:'Administrador',password:'senha-teste',storeName:'Loja Teste'});call('operators.authenticate',{username:'Mestre',password:'senha-teste'});}
const product={id:'p',name:'Produto',priceInCents:1000,category:'Categoria',active:true,emoji:'P'};let session;if(open&&configure){call('catalog.save',{products:[product]});session=call('cash.open',{requestId:'open',amountInCents:10000,operatorId});}
const complete=(requestId='sale',payments=[{method:'pix',amountInCents:1000}],quantity=1,owner=1)=>call('sales.complete',{requestId,items:[{productId:product.id,quantity,unitPriceInCents:1000}],totalInCents:1000*quantity,payments,cashSessionId:session.id},owner);
const amounts=(method,amount)=>({cash:0,pix:0,debit:0,credit:0,customer_credit:0,[method]:amount});
const issue=(quantity=2)=>{const sale=complete('origin',[{method:'pix',amountInCents:1000*quantity}],quantity);call('sales.cancel',{requestId:'origin-cancel',id:sale.id,reason:'customer_cancelled'});const result=call('financial.settle',{requestId:'issue',saleId:sale.id,amounts:amounts('customer_credit',1000*quantity),cashSessionId:session.id});const credit=result.issuedCredits[0],code=backend.receipt(1,credit.id).authCode;return {credit,code,sale,result};};
return {profile,get database(){return database;},get backend(){return backend;},operatorId,product,session,call,complete,amounts,issue,advance:ms=>{time+=ms;},reopen:nextMigrations=>{database.close();if(nextMigrations)migrations=nextMigrations;create();},login:(owner=1)=>call('operators.authenticate',{username:'Mestre',password:'senha-teste'},owner),vault:custody};}
module.exports={fixture,vault};
