import type { Product, CartItem } from '../../src/types/product';
import type { StoreSettings, CashOperator } from '../../src/types/settings';
import type { Sale, SaleCancellationReason } from '../../src/types/sale';
import type { SaleFinancialData, MerchandiseReturn, FinancialRefund } from '../../src/types/customerCredit';
import type { FinancialSnapshot, PublicCredit, Settlement } from '../../src/persistence/contracts';
import type { SalePayment } from '../../src/types/payment';
import type { CashData, CashMovement, CashSession } from '../../src/types/cash';
import type { CashPaymentTotals } from '../../src/domain/cash';
export type Request<T> = T & { requestId: string };
export type InstallationDto = { status: 'testing'|'ready_for_setup'|'production'; generation: number };
export type FinancialOperation='sales.complete'|'sales.cancel'|'cash.open'|'cash.recordMovement'|'cash.close'|'financial.recordReturn'|'financial.settle'|'financial.updateRefund'|'financial.recover';
export interface Operations {
  'operators.authenticate': { input: {username:string; password:string}; output: CashOperator };
  'operators.reauthenticate': { input: {password:string}; output: null };
  'operators.current': { input: Record<string,never>; output: CashOperator|null };
  'operators.logout': { input: Record<string,never>; output: null };
  'operators.list': { input: Record<string,never>; output: CashOperator[] };
  'catalog.list': { input: Record<string,never>; output: Product[] };
  'catalog.save': { input: {products:Product[]}; output: null };
  'settings.read': { input: Record<string,never>; output: StoreSettings };
  'settings.update': { input: {settings:StoreSettings; passwords:Record<string,string>}; output: StoreSettings };
  'installation.read': { input: Record<string,never>; output: InstallationDto };
  'sales.list': { input: Record<string,never>; output: Sale[] };
  'sales.get': { input: {id:string}; output: Sale|null };
  'sales.complete': { input: Request<{items:Array<{productId:string;quantity:number;unitPriceInCents:number}>;totalInCents:number;payments:SalePayment[];cashSessionId:string}>; output: Sale };
  'sales.cancel': { input: Request<{id:string; reason:SaleCancellationReason; note?:string}>; output: Sale };
  'cash.read': { input: Record<string,never>; output: CashData };
  'cash.open': { input: Request<{amountInCents:number; operatorId:string}>; output: CashSession };
  'cash.recordMovement': { input: Request<{sessionId:string; type:CashMovement['type']; amountInCents:number; description:string}>; output: CashMovement };
  'cash.close': { input: Request<{sessionId:string; counts:CashPaymentTotals; reviewedFingerprint:string}>; output: CashSession };
  'financial.snapshot': { input: Record<string,never>; output: FinancialSnapshot };
  'financial.recordReturn': { input: Request<{saleId:string; quantities:Record<string,number>; cashSessionId?:string; reason?:string}>; output: MerchandiseReturn };
  'financial.settle': { input: Request<Omit<Settlement,'requestId'> & {saleId:string}>; output: {refunds:FinancialRefund[]; issuedCredits:PublicCredit[]} };
  'financial.updateRefund': { input: Request<{id:string; status:'completed'|'failed'; cashSessionId?:string}>; output: FinancialRefund };
  'financial.recover': { input: {requestId:string}; output: null };
  'credits.list': { input: {query:string}; output: PublicCredit[] };
  'credits.authorize': { input: {query:string; code:string}; output: PublicCredit|null };
  'credits.printReceipt': { input: {creditId:string}; output: null };
  'credits.readMovements': { input: {creditId:string}; output: SaleFinancialData['creditMovements'] };
  'operations.prepare': {input:{kind:FinancialOperation;payload:unknown};output:{requestId:string}};
  'operations.acknowledge': {input:{requestId:string};output:null};
  'operations.discardPrepared': {input:{requestId:string};output:null};
  'operations.list': {input:Record<string,never>;output:Array<{requestId:string;kind:string;status:string;createdAt:string}>};
  'operations.read': { input: {requestId:string}; output: {status:'unknown'|'prepared'|'committed'|'interrupted'; result?:unknown} };
  'draft.read': { input: Record<string,never>; output: CartItem[] };
  'draft.save': { input: {items:CartItem[]}; output: null };
}
export type Operation = keyof Operations;
export type Reply<T> = {ok:true;value:T}|{ok:false;error:{code:string}};
export type DomainApi = {readonly [K in Operation]: (input:Operations[K]['input'])=>Promise<Operations[K]['output']>};
export const operationNames = ['operators.authenticate','operators.reauthenticate','operators.current','operators.logout','operators.list','catalog.list','catalog.save','settings.read','settings.update','installation.read','sales.list','sales.get','sales.complete','sales.cancel','cash.read','cash.open','cash.recordMovement','cash.close','financial.snapshot','financial.recordReturn','financial.settle','financial.updateRefund','financial.recover','credits.list','credits.authorize','credits.printReceipt','credits.readMovements','operations.prepare','operations.acknowledge','operations.discardPrepared','operations.list','operations.read','draft.read','draft.save'] as const satisfies readonly Operation[];
